apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silllypy
  annotations:
    github.com/project-slug: vtsarfin/silllypy
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
